plugins:
  - serverless-dotenv-plugin

app: ${env:APP_NAME}
service: vision
frameworkVersion: '4'
org: ${env:ORG_NAME}

provider:
  name: aws
  runtime: python3.12
  region: ${env:REGION}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:GetObject
      Resource:
        - arn:aws:s3:::${env:BUCKET_NAME}/*
    - Effect: Allow
      Action:
        - rekognition:DetectFaces
        - rekognition:DetectLabels
      Resource: "*"
    - Effect: Allow
      Action:
        - logs:CreateLogGroup
        - logs:CreateLogStream
        - logs:PutLogEvents
      Resource: "*"
    - Effect: Allow
      Action:
        - bedrock:InvokeModel
      Resource: "*"

functions:
  health:
    handler: handler.health
    events:
      - httpApi:
          path: /
          method: get
  v1Description:
    handler: handler.v1_description
    events:
      - httpApi:
          path: /v1
          method: get
  v2Description:
    handler: handler.v2_description
    events:
      - httpApi:
          path: /v2
          method: get
  faceEmotionAnalysisV1:
    handler: handler.face_emotion_analysis_v1
    events:
      - httpApi:
          path: /v1/vision
          method: post
  faceAndPetAnalysisV2:
    handler: handler.face_and_pet_analysis_v2
    timeout: 30
    events:
      - httpApi:
          path: /v2/vision
          method: post

resources:
  Resources:
    MyBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${env:BUCKET_NAME}