service: vision
frameworkVersion: '4'

provider:
  name: aws
  runtime: python3.9
  region: us-east-1

functions:
  health:
    handler: handler.health
    events:
      - httpApi:
          path: /
          method: get
  v1Description:
    handler: handler.v1_description
    events:
      - httpApi:
          path: /v1
          method: get
  v2Description:
    handler: handler.v2_description
    events:
      - httpApi:
          path: /v2
          method: get
  faceEmotionAnalysisV1:
    handler: handler.face_emotion_analysis_v1
    events:
      - httpApi:
          path: /v1/vision
          method: post
  faceAndPetAnalysisV2:
    handler: handler.face_and_pet_analysis_v2
    events:
      - httpApi:
          path: /v2/vision
          method: post
